version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: b3_website
    ports:
      - "85:80"
    volumes:
      - ./bcube-website-2.0:/usr/share/nginx/html
    networks:
      - frontend
    restart: always

networks:
  frontend:
    external:
      name: frontend
