version: "3"

services:
  bind9:
    container_name: local-dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Karachi
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: always
    user: "root:bind"  # Set the user and group ownership for the container
    networks:
      frontend:
        ipv4_address: 10.10.0.4  # Assign a specific IP address
      # backend:
      #   ipv4_address: 10.20.0.4  # Assign a specific IP address

networks:
  frontend:
    external: true
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"
  # backend:
  #   external: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "10.20.0.0/24"