version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: '3306'
      DB_MYSQL_USER: 'dbuser'
      DB_MYSQL_PASSWORD: 'Katana12!@'
      DB_MYSQL_NAME: 'homelab-db'
      EXTRA_HOSTS: "host.docker.internal:host-gateway"
      DEBUG: 'true'
    
    networks:
      frontend:
        # ipv4_address: 10.10.0.6  # Assign a specific IP address
      backend:
        # ipv4_address: 10.20.0.6  # Assign a specific IP address
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Katana12!@'
      MYSQL_DATABASE: 'homelab-db'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'Katana12!@'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      backend:
        # ipv4_address: 10.20.0.7  # Assign a specific IP address

networks:
  frontend:
    external: true
  backend:
    external: true

# Update MySQL User Authentication Method:
# Access the MySQL container using the following command:

# bash
# Copy code
# docker exec -it <mysql_container_name> mysql -u root -p 
# Katana12!@
# Replace <mysql_container_name> with the actual name of your MySQL container.

# Once you're inside the MySQL shell, run the following SQL query to update the authentication method for your user. Replace 'your_database_user' and 'your_new_password' with your actual database user and a new password.
# ALTER USER 'dbuser'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'Katana12!@';

# Flush privileges to apply the changes:
# FLUSH PRIVILEGES;

# Exit the MySQL shell:
# EXIT;