version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: '3306'
      DB_MYSQL_USER: 'your_database_user'
      DB_MYSQL_PASSWORD: 'your_database_password'
      DB_MYSQL_NAME: 'your_database_name'
    
    networks:
      frontend:
        ipv4_address: 10.10.0.6  # Assign a specific IP address
      backend:
        ipv4_address: 10.20.0.6  # Assign a specific IP address

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'your_root_password'
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_database_user'
      MYSQL_PASSWORD: 'your_database_password'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 10.20.0.7  # Assign a specific IP address

networks:
  frontend:
    external: true
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"
  backend:
    external: true
    ipam:
      driver: default
      config:
        - subnet: "10.20.0.0/24"

# Update MySQL User Authentication Method:
# Access the MySQL container using the following command:

# bash
# Copy code
# docker exec -it <mysql_container_name> mysql -u root -p 
# your_root_password
# Replace <mysql_container_name> with the actual name of your MySQL container.

# Once you're inside the MySQL shell, run the following SQL query to update the authentication method for your user. Replace 'your_database_user' and 'your_new_password' with your actual database user and a new password.

# sql
# Copy code
# ALTER USER 'your_database_user'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'your_database_password';
# Flush privileges to apply the changes:

# sql
# Copy code
# FLUSH PRIVILEGES;
# Exit the MySQL shell:

# sql
# Copy code
# EXIT;